using System;
using System.Drawing;
 
class FontMetrics
{
	static void Main(string[] args)
	{
		PrintEmHeight("Andalus");
		PrintEmHeight("Angsana New");
		PrintEmHeight("AngsanaUPC");
		PrintEmHeight("Aparajita");
		PrintEmHeight("Arabic Typesetting");
		PrintEmHeight("Arial");
		PrintEmHeight("Arial Black");
		PrintEmHeight("Batang");
		PrintEmHeight("BatangChe");
		PrintEmHeight("Browallia New");
		PrintEmHeight("BrowalliaUPC");
		PrintEmHeight("Calibri");
		PrintEmHeight("Cambria");
		PrintEmHeight("Cambria Math");
		PrintEmHeight("Comic Sans MS");
		PrintEmHeight("Consolas");
		PrintEmHeight("Constantia");
		PrintEmHeight("Corbel");
		PrintEmHeight("Cordia New");
		PrintEmHeight("CordiaUPC");
		PrintEmHeight("Courier New");
		PrintEmHeight("DaunPenh");
		PrintEmHeight("David");
		PrintEmHeight("DejaVu Sans");
		PrintEmHeight("DejaVu Sans Mono");
		PrintEmHeight("DejaVu Serif");
		PrintEmHeight("DFKai-SB");
		PrintEmHeight("DilleniaUPC");
		PrintEmHeight("DokChampa");
		PrintEmHeight("Dotum");
		PrintEmHeight("DotumChe");
		PrintEmHeight("Dutch801 SWC");
		PrintEmHeight("Ebrima");
		PrintEmHeight("Estrangelo Edessa");
		PrintEmHeight("EucrosiaUPC");
		PrintEmHeight("Euphemia");
		PrintEmHeight("FangSong");
		PrintEmHeight("Franklin Gothic Medium");
		PrintEmHeight("FrankRuehl");
		PrintEmHeight("FreesiaUPC");
		PrintEmHeight("Gabriola");
		PrintEmHeight("Gautami");
		PrintEmHeight("Gentium Basic");
		PrintEmHeight("Gentium Book Basic");
		PrintEmHeight("Georgia");
		PrintEmHeight("Gisha");
		PrintEmHeight("Gulim");
		PrintEmHeight("GulimChe");
		PrintEmHeight("Gungsuh");
		PrintEmHeight("GungsuhChe");
		PrintEmHeight("Impact");
		PrintEmHeight("IrisUPC");
		PrintEmHeight("Iskoola Pota");
		PrintEmHeight("JasmineUPC");
		PrintEmHeight("KaiTi");
		PrintEmHeight("Kalinga");
		PrintEmHeight("Kartika");
		PrintEmHeight("Khmer UI");
		PrintEmHeight("KodchiangUPC");
		PrintEmHeight("Kokila");
		PrintEmHeight("Lao UI");
		PrintEmHeight("Latha");
		PrintEmHeight("Leelawadee");
		PrintEmHeight("Levenim MT");
		PrintEmHeight("Liberation Sans Narrow");
		PrintEmHeight("LilyUPC");
		PrintEmHeight("Lingoes Unicode");
		PrintEmHeight("Linux Biolinum G");
		PrintEmHeight("Linux Libertine G");
		PrintEmHeight("Lucida Console");
		PrintEmHeight("Lucida Sans Unicode");
		PrintEmHeight("Malgun Gothic");
		PrintEmHeight("Mangal");
		PrintEmHeight("Meiryo UI");
		PrintEmHeight("Microsoft Himalaya");
		PrintEmHeight("Microsoft JhengHei");
		PrintEmHeight("Microsoft New Tai Lue");
		PrintEmHeight("Microsoft PhagsPa");
		PrintEmHeight("Microsoft Sans Serif");
		PrintEmHeight("Microsoft Tai Le");
		PrintEmHeight("Microsoft Uighur");
		PrintEmHeight("Microsoft YaHei");
		PrintEmHeight("Microsoft Yi Baiti");
		PrintEmHeight("MingLiU");
		PrintEmHeight("MingLiU_HKSCS");
		PrintEmHeight("MingLiU_HKSCS-ExtB");
		PrintEmHeight("MingLiU-ExtB");
		PrintEmHeight("Miriam Fixed");
		PrintEmHeight("Miriam");
		PrintEmHeight("Mongolian Baiti");
		PrintEmHeight("MoolBoran");
		PrintEmHeight("‚l‚r ‚oƒSƒVƒbƒN");
		PrintEmHeight("‚l‚r ‚o–¾’©");
		PrintEmHeight("MS UI Gothic");
		PrintEmHeight("‚l‚r ƒSƒVƒbƒN");
		PrintEmHeight("‚l‚r –¾’©");
		PrintEmHeight("MV Boli");
		PrintEmHeight("Narkisim");
		PrintEmHeight("NSimSun");
		PrintEmHeight("Nyala");
		PrintEmHeight("OpenSymbol");
		PrintEmHeight("Palatino Linotype");
		PrintEmHeight("Plantagenet Cherokee");
		PrintEmHeight("PMingLiU");
		PrintEmHeight("PMingLiU-ExtB");
		PrintEmHeight("Raavi");
		PrintEmHeight("Rod");
		PrintEmHeight("Sakkal Majalla");
		PrintEmHeight("Segoe Print");
		PrintEmHeight("Segoe Script");
		PrintEmHeight("Segoe UI");
		PrintEmHeight("Segoe UI Symbol");
		PrintEmHeight("Shonar Bangla");
		PrintEmHeight("Shruti");
		PrintEmHeight("SimHei");
		PrintEmHeight("Simplified Arabic");
		PrintEmHeight("Simplified Arabic Fixed");
		PrintEmHeight("SimSun");
		PrintEmHeight("SimSun-ExtB");
		PrintEmHeight("Swiss742 SWC");
		PrintEmHeight("Sylfaen");
		PrintEmHeight("Symbol");
		PrintEmHeight("Tahoma");
		PrintEmHeight("Times New Roman");
		PrintEmHeight("Traditional Arabic");
		PrintEmHeight("Trebuchet MS");
		PrintEmHeight("Tunga");
		PrintEmHeight("Utsaah");
		PrintEmHeight("Vani");
		PrintEmHeight("Verdana");
		PrintEmHeight("Vijaya");
		PrintEmHeight("Vrinda");
		PrintEmHeight("Webdings");
		PrintEmHeight("Wingdings");
		PrintEmHeight("Meiryo");
	}
	
	static void PrintEmHeight(String name) {
		FontFamily fontFamily = new FontFamily(name);
		int emheight =  fontFamily.GetEmHeight(FontStyle.Regular);
		int ascent = fontFamily.GetCellAscent(FontStyle.Regular);
		int descent = fontFamily.GetCellDescent(FontStyle.Regular);
		
		if (emheight != ascent + descent) {
			Console.WriteLine("font-emheight." + name.Replace(" ", "\\u0020") + " =  " + (emheight / (double)(ascent + descent)));
		}
	}
}
